---
title: "Probability Theory"
author: "Sriramkumar Sarida"

---

# Assignment 1 

------------------------------------------------------------------------

**T** - *Being on time*  
**T_not** - *Not being on time*  
**S** - *Change in Scope*  
**S_not** - *No change in scope*  

> Defining the probabilities from the probability tree  

```{r}
P_S <- 0.3 
P_S_not <- 0.7  
P_T_given_S <- 0.2  
P_T_given_S_not <- 0.6  
```

**P(T ∩ S)** - *P_T_and_S*  
**(T ∩ ¬S)** - *P_T_and_S_not*  
**P(¬T ∩ S)** - *P_not_T_and_S*  
**P(¬T ∩ ¬S)** - *P_not_T_and_S_not*  

```{r}
P_T_and_S <- P_S * P_T_given_S  
P_T_and_S_not <- P_S_not * P_T_given_S_not  
P_not_T_and_S <- P_S * (1 - P_T_given_S)  
P_not_T_and_S_not <- P_S_not * (1 - P_T_given_S_not)  
```

```{r}
P_T_and_S  
P_T_and_S_not  
P_not_T_and_S  
P_not_T_and_S_not  
```

> Sum of all probabilities  

```{r}
probabilities_sum <- P_T_and_S + P_T_and_S_not + P_not_T_and_S + P_not_T_and_S_not
```

```{r}
probabilities_sum
```


# Assignment 2

------------------------------------------------------------------------

> Information from the Venn Diagram 

```{r}
percentage_all_three_devices <- 0.5 
percentage_smartphone_tablet <- 7.3  
percentage_tablet_computer <- 3.3  
percentage_smartphone_computer <- 8.8  
percentage_smartphone = 42.3  
percentage_tablet = 27.8  
percentage_computer = 10  

```

```{r}
# What is the percentage of customers using all three devices?
percentage_all_three_devices
```


```{r}
# What is the percentage of customers using at least two devices?
percentage_atleast_two_devices <- percentage_all_three_devices + percentage_smartphone_tablet + percentage_tablet_computer + percentage_smartphone_computer 

percentage_atleast_two_devices
```

```{r}
#What is the percentage of customers using only one device?
percentage_one_device <- percentage_smartphone + percentage_tablet + percentage_computer

percentage_one_device
```


# Assignment 3

------------------------------------------------------------------------

> Information from the Application

```{r}
P_B_given_A = 0.97
P_B_given_A_not = 0.01
P_A = 0.04
P_A_not <- 1 - P_A

P_A_not

```

> We are required to find:  
- Probability that the product is faulty given that the alarm has gone off -- **P_A_given_B**  
- Probability that the product is not faulty given that the alarm has gone off -- **P_A_not_given_B**


```{r}
P_B = P_B_given_A * P_A + P_B_given_A_not * P_A_not

P_B
```

```{r}
P_A_given_B = (P_B_given_A * P_A) / P_B

P_A_given_B
```

```{r}
P_A_not_given_B = (P_B_given_A_not * P_A_not) / P_B

P_A_not_given_B
```

```{r}
cat("# P_A_not_given_B =", P_A_not_given_B * 100, "% that the product is flawless and a")

cat("# P_A_given_B =", P_A_given_B * 100, "% that the product is faulty")
```

