---
title: "Causality"
author: "Sriramkumar Sarida"
---


# Famous example: Nicolas Cage films and number of poeple drowned by falling into a pool

I came across this devious example of the number of people drowned by falling into a pool correlated with films Nicolas Cage appeared in during the same time period. I would like to recreate this example: https://www.datasciencecentral.com/wp-content/uploads/2021/10/2808309983.png

```{r}
set.seed(99) # for reproducibility
years <- 2000:2009
cage_films <- cumsum(sample(1:5, 10, replace = TRUE))
drownings <- cumsum(sample(1:5, 10, replace = TRUE)) + rnorm(10, mean = 0, sd = 0.15)
data <- data.frame(Year = years, Cage_Films = cage_films, Drownings = drownings)

```


```{r}
data
```


```{r}
library(ggplot2)

# Line plot showing trends over time
ggplot(data, aes(x = Year)) + 
  geom_line(aes(y = Cage_Films, colour = "Nicolas Cage Films")) +
  geom_line(aes(y = Drownings, colour = "Drownings by falling into the pool")) +
  labs(title = "Spurious Correlation between Nicolas Cage Films and Drownings",
       y = "Count",
       colour = "Legend") +
  theme_minimal()

# Scatter plot showing the correlation
ggplot(data, aes(x = Cage_Films, y = Drownings)) +
  geom_point() +
  labs(title = "Scatter Plot of Nicolas Cage Films vs Drownings",
       x = "Nicolas Cage Films",
       y = "Drownings by falling into the pool") +
  theme_minimal()
```

