project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Probability Theory"
            file: content/01_journal/01_probability.qmd
          - text: "02 Statistical Concepts"
            file: content/01_journal/02_statistics.qmd
          - text: "03 Regression and Statistical Inference"
            file: content/01_journal/03_regression.qmd
          - text: "04 Causality"
            file: content/01_journal/04_causality.qmd
          - text: "05 Directed Acyclic Graphs"
            file: content/01_journal/05_dag.qmd
          - text: "06 Randomized Controlled Trials"
            file: content/01_journal/06_rct.qmd
          - text: "07 Matching and Subclassification"
            file: content/01_journal/07_matching.qmd
          - text: "08 Difference-in-Differences"
            file: content/01_journal/08_did.qmd
          - text: "09 Instrumental Variables"
            file: content/01_journal/09_iv.qmd
          - text: "10 Regression Discontinuity"
            file: content/01_journal/10_rdd.qmd            

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto