{
  "hash": "4598399a00cde014ee8dacaacc56a2bc",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\nauthor: \"Sriramkumar Sarida\"\n---\n\n\n# Parking Spot (DAG)\n\n------------------------------------------------------------------------\n\n-   This seems to be similar to the Confounding DAG explained in the theory. The **parking spots** seems to be the *treatment variable* and **store sales** would be the *outcome variable*. The *confounding* variable would be the **location**, as it makes a difference to the store sales if the location of the store is the city center or in the Urban areas.\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_41ea7e5bf465e83bdd18a4de6e79e634'}\n\n```{.r .cell-code}\n# Assuming you have the ggdag package installed\nlibrary(ggdag)\n\n# Define the DAG\ndag <- dagify(\n  X ~ Z,\n  Y ~ Z,\n  X ~ Y,\n  coords = list(x = c(Y = 3, Z = 2, X = 1),\n                y = c(Y = 0, Z = 1, X = 0)),\n  labels = list(X = \"Sales\",\n                Y = \"Parking_Spots\",\n                Z = \"Location\")\n)\n\nggdag(dag) +\n  theme_dag() + \n  geom_dag_point() +\n  geom_dag_text() +\n  geom_dag_edges() +\n  geom_dag_label_repel(aes(label = label))\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n# Company sells a SaaS\n\n------------------------------------------------------------------------\n\n> Load the data frame\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_96745682d4f1b77186888290e49f7097'}\n\n```{.r .cell-code}\ncustomer_sat <- readRDS(\"../../data/customer_sat.rds\")\n```\n:::\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_40cb90769ad0cfadda5861e4f94049e0'}\n\n```{.r .cell-code}\nsummary(customer_sat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>    follow_ups      satisfaction   subscription      \n#>  Min.   : 0.000   Min.   :40.00   Length:15         \n#>  1st Qu.: 2.500   1st Qu.:48.50   Class :character  \n#>  Median : 7.000   Median :60.00   Mode  :character  \n#>  Mean   : 5.667   Mean   :60.13                     \n#>  3rd Qu.: 8.000   3rd Qu.:72.00                     \n#>  Max.   :10.000   Max.   :80.00\n```\n:::\n\n```{.r .cell-code}\n# Seeing the datatypes of the dataframe\nstr(customer_sat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> tibble [15 × 3] (S3: tbl_df/tbl/data.frame)\n#>  $ follow_ups  : num [1:15] 8 7 8 9 10 6 7 6 8 8 ...\n#>  $ satisfaction: num [1:15] 40 45 47 44 50 55 60 62 59 65 ...\n#>  $ subscription: chr [1:15] \"Elite\" \"Elite\" \"Elite\" \"Elite\" ...\n```\n:::\n\n```{.r .cell-code}\nhead(customer_sat)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"follow_ups\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"satisfaction\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"subscription\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"8\",\"2\":\"40\",\"3\":\"Elite\"},{\"1\":\"7\",\"2\":\"45\",\"3\":\"Elite\"},{\"1\":\"8\",\"2\":\"47\",\"3\":\"Elite\"},{\"1\":\"9\",\"2\":\"44\",\"3\":\"Elite\"},{\"1\":\"10\",\"2\":\"50\",\"3\":\"Elite\"},{\"1\":\"6\",\"2\":\"55\",\"3\":\"Premium+\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## regress satisfaction on follow_ups\n\n> Run a linear regression on the customer_sat\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_b310edcc5143da362608767bd7a3769d'}\n\n```{.r .cell-code}\nlm_model <- lm(satisfaction ~ follow_ups, data = customer_sat)\n\nsummary(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = customer_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n:::\n\n\n## regress satisfaction on follow_ups and account for subscription\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-5_faff5106945ade2b2f998680df3127b3'}\n\n```{.r .cell-code}\ncustomer_sat$subscription <- as.factor(customer_sat$subscription)\nlm_model_subscription <- lm(satisfaction ~ follow_ups + subscription, data = customer_sat)\n\nsummary(lm_model_subscription)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = customer_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n\n# Compare the coefficients and find a possible explanation.\n\n-   For the model **without a subscription,** the coefficient is **-3.3093**. This negative coefficient indicates that without a subscription, follow ups decrease the satisfaction level of the customers\n\n-   For the model **with a subscription**, the coefficient is **2.1944.** This positive coefficient indicates that with a subscription, follows_ups increases the satisfaction level of the customers. **Premium** coefficient is +44.7222, indicating that being on this subscription level is associated with a 44.7222 point increase in satisfaction compared to the base category. **Elite** coefficient is +18.0722, indicating that being on this subscription level is associated with an 18.0722 point increase in satisfaction compared to the base category.\n\n-    I believe customers find it intrusive when they are being followed up without any subscription. They probablyy have fewers features as well, so this might be the cause for the negative impact. On the other hand, the premium and elite customers find it better with the follow ups.\n\n-   As mentioned in the previous point, a similar impact is also seen on the variance R^2^ and R^2^ (Adjusted). Both the values increased, as the model now captures more of the variance in satisfaction. This makes subscription level an important factor in explaining customer satisfaction.\n\n\n# Plot the data\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-6_d050f53925082475491036ee085e738d'}\n\n```{.r .cell-code}\nlibrary(ggdag)\n\n# Define the DAG\ndag_customer_satisfaction <- dagify(\n  Z ~ X,\n  Z ~ Y,\n  Y ~ X,\n  coords = list(x = c(Y = 3, Z = 2, X = 1),\n                y = c(Y = 0, Z = 1, X = 0)),\n  labels = list(X = \"Subscription \",\n                Y = \"Follow_ups\",\n                Z = \"Satisfaction\")\n)\n\nggdag(dag_customer_satisfaction) +\n  theme_dag() + \n  geom_dag_point() +\n  geom_dag_text() +\n  geom_dag_edges() +\n  geom_dag_label_repel(aes(label = label))\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}