{
  "hash": "b1774bb87f5185d0f301ea7398605f32",
  "result": {
    "markdown": "---\ntitle: \"Statistical Concepts\"\nauthor: \"Sriramkumar Sarida\"\n---\n\n\n> Load the data variable:\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-1_c557ce6fdab3fc5a543e4e61cdea1c47'}\n\n```{.r .cell-code}\nrandom_vars <- readRDS(\"../../data/random_vars.rds\")\n\nView(random_vars)\n\nrandom_vars\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"age\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"income\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"21\",\"2\":\"940\"},{\"1\":\"34\",\"2\":\"6678\"},{\"1\":\"10\",\"2\":\"22\"},{\"1\":\"68\",\"2\":\"2392\"},{\"1\":\"15\",\"2\":\"74\"},{\"1\":\"50\",\"2\":\"5012\"},{\"1\":\"32\",\"2\":\"6636\"},{\"1\":\"14\",\"2\":\"36\"},{\"1\":\"17\",\"2\":\"1365\"},{\"1\":\"26\",\"2\":\"3763\"},{\"1\":\"8\",\"2\":\"59\"},{\"1\":\"28\",\"2\":\"3600\"},{\"1\":\"12\",\"2\":\"79\"},{\"1\":\"34\",\"2\":\"5327\"},{\"1\":\"28\",\"2\":\"4425\"},{\"1\":\"59\",\"2\":\"9431\"},{\"1\":\"21\",\"2\":\"2914\"},{\"1\":\"20\",\"2\":\"515\"},{\"1\":\"19\",\"2\":\"979\"},{\"1\":\"33\",\"2\":\"6253\"},{\"1\":\"24\",\"2\":\"3922\"},{\"1\":\"43\",\"2\":\"3988\"},{\"1\":\"35\",\"2\":\"3655\"},{\"1\":\"34\",\"2\":\"7646\"},{\"1\":\"29\",\"2\":\"3691\"},{\"1\":\"18\",\"2\":\"3738\"},{\"1\":\"28\",\"2\":\"2409\"},{\"1\":\"15\",\"2\":\"64\"},{\"1\":\"13\",\"2\":\"23\"},{\"1\":\"15\",\"2\":\"27\"},{\"1\":\"52\",\"2\":\"4988\"},{\"1\":\"7\",\"2\":\"23\"},{\"1\":\"16\",\"2\":\"55\"},{\"1\":\"46\",\"2\":\"3462\"},{\"1\":\"29\",\"2\":\"3318\"},{\"1\":\"21\",\"2\":\"653\"},{\"1\":\"26\",\"2\":\"555\"},{\"1\":\"7\",\"2\":\"4\"},{\"1\":\"34\",\"2\":\"2733\"},{\"1\":\"59\",\"2\":\"9420\"},{\"1\":\"16\",\"2\":\"20\"},{\"1\":\"59\",\"2\":\"6285\"},{\"1\":\"26\",\"2\":\"790\"},{\"1\":\"3\",\"2\":\"53\"},{\"1\":\"58\",\"2\":\"3413\"},{\"1\":\"53\",\"2\":\"4272\"},{\"1\":\"39\",\"2\":\"6786\"},{\"1\":\"56\",\"2\":\"7745\"},{\"1\":\"28\",\"2\":\"2954\"},{\"1\":\"17\",\"2\":\"686\"},{\"1\":\"47\",\"2\":\"2586\"},{\"1\":\"37\",\"2\":\"8244\"},{\"1\":\"48\",\"2\":\"5983\"},{\"1\":\"30\",\"2\":\"5081\"},{\"1\":\"45\",\"2\":\"2215\"},{\"1\":\"79\",\"2\":\"1009\"},{\"1\":\"35\",\"2\":\"7372\"},{\"1\":\"17\",\"2\":\"2386\"},{\"1\":\"31\",\"2\":\"8069\"},{\"1\":\"4\",\"2\":\"22\"},{\"1\":\"48\",\"2\":\"9167\"},{\"1\":\"18\",\"2\":\"2594\"},{\"1\":\"13\",\"2\":\"1\"},{\"1\":\"21\",\"2\":\"1128\"},{\"1\":\"45\",\"2\":\"5571\"},{\"1\":\"31\",\"2\":\"7219\"},{\"1\":\"18\",\"2\":\"2747\"},{\"1\":\"39\",\"2\":\"6936\"},{\"1\":\"66\",\"2\":\"1439\"},{\"1\":\"37\",\"2\":\"4102\"},{\"1\":\"19\",\"2\":\"2696\"},{\"1\":\"45\",\"2\":\"3762\"},{\"1\":\"13\",\"2\":\"73\"},{\"1\":\"44\",\"2\":\"5010\"},{\"1\":\"32\",\"2\":\"6070\"},{\"1\":\"42\",\"2\":\"8429\"},{\"1\":\"21\",\"2\":\"2449\"},{\"1\":\"16\",\"2\":\"69\"},{\"1\":\"21\",\"2\":\"4321\"},{\"1\":\"10\",\"2\":\"14\"},{\"1\":\"47\",\"2\":\"5532\"},{\"1\":\"17\",\"2\":\"3093\"},{\"1\":\"8\",\"2\":\"35\"},{\"1\":\"69\",\"2\":\"1105\"},{\"1\":\"14\",\"2\":\"3\"},{\"1\":\"60\",\"2\":\"3762\"},{\"1\":\"22\",\"2\":\"2937\"},{\"1\":\"47\",\"2\":\"5978\"},{\"1\":\"26\",\"2\":\"3079\"},{\"1\":\"12\",\"2\":\"86\"},{\"1\":\"21\",\"2\":\"359\"},{\"1\":\"24\",\"2\":\"3944\"},{\"1\":\"40\",\"2\":\"3974\"},{\"1\":\"50\",\"2\":\"4851\"},{\"1\":\"31\",\"2\":\"6560\"},{\"1\":\"4\",\"2\":\"14\"},{\"1\":\"49\",\"2\":\"6020\"},{\"1\":\"46\",\"2\":\"7574\"},{\"1\":\"71\",\"2\":\"995\"},{\"1\":\"45\",\"2\":\"9929\"},{\"1\":\"2\",\"2\":\"80\"},{\"1\":\"32\",\"2\":\"5521\"},{\"1\":\"22\",\"2\":\"2287\"},{\"1\":\"24\",\"2\":\"2461\"},{\"1\":\"41\",\"2\":\"5893\"},{\"1\":\"33\",\"2\":\"3241\"},{\"1\":\"36\",\"2\":\"4479\"},{\"1\":\"20\",\"2\":\"2884\"},{\"1\":\"70\",\"2\":\"1018\"},{\"1\":\"53\",\"2\":\"7567\"},{\"1\":\"29\",\"2\":\"3067\"},{\"1\":\"76\",\"2\":\"2437\"},{\"1\":\"72\",\"2\":\"1992\"},{\"1\":\"49\",\"2\":\"8439\"},{\"1\":\"72\",\"2\":\"2207\"},{\"1\":\"16\",\"2\":\"55\"},{\"1\":\"30\",\"2\":\"1939\"},{\"1\":\"12\",\"2\":\"90\"},{\"1\":\"42\",\"2\":\"5021\"},{\"1\":\"13\",\"2\":\"89\"},{\"1\":\"22\",\"2\":\"3407\"},{\"1\":\"32\",\"2\":\"5730\"},{\"1\":\"26\",\"2\":\"2876\"},{\"1\":\"27\",\"2\":\"2890\"},{\"1\":\"41\",\"2\":\"7102\"},{\"1\":\"8\",\"2\":\"2\"},{\"1\":\"48\",\"2\":\"4111\"},{\"1\":\"8\",\"2\":\"96\"},{\"1\":\"27\",\"2\":\"273\"},{\"1\":\"31\",\"2\":\"4500\"},{\"1\":\"40\",\"2\":\"1681\"},{\"1\":\"44\",\"2\":\"7866\"},{\"1\":\"26\",\"2\":\"604\"},{\"1\":\"43\",\"2\":\"4126\"},{\"1\":\"7\",\"2\":\"47\"},{\"1\":\"52\",\"2\":\"4647\"},{\"1\":\"45\",\"2\":\"2755\"},{\"1\":\"52\",\"2\":\"3645\"},{\"1\":\"14\",\"2\":\"93\"},{\"1\":\"57\",\"2\":\"10422\"},{\"1\":\"82\",\"2\":\"2152\"},{\"1\":\"18\",\"2\":\"4222\"},{\"1\":\"27\",\"2\":\"3960\"},{\"1\":\"34\",\"2\":\"6075\"},{\"1\":\"49\",\"2\":\"7781\"},{\"1\":\"36\",\"2\":\"6328\"},{\"1\":\"10\",\"2\":\"38\"},{\"1\":\"31\",\"2\":\"2821\"},{\"1\":\"9\",\"2\":\"29\"},{\"1\":\"28\",\"2\":\"1775\"},{\"1\":\"34\",\"2\":\"2378\"},{\"1\":\"33\",\"2\":\"6623\"},{\"1\":\"47\",\"2\":\"5671\"},{\"1\":\"42\",\"2\":\"5239\"},{\"1\":\"61\",\"2\":\"4199\"},{\"1\":\"41\",\"2\":\"5187\"},{\"1\":\"13\",\"2\":\"76\"},{\"1\":\"14\",\"2\":\"65\"},{\"1\":\"67\",\"2\":\"823\"},{\"1\":\"59\",\"2\":\"4790\"},{\"1\":\"68\",\"2\":\"1528\"},{\"1\":\"31\",\"2\":\"2819\"},{\"1\":\"31\",\"2\":\"3710\"},{\"1\":\"52\",\"2\":\"6719\"},{\"1\":\"19\",\"2\":\"2036\"},{\"1\":\"27\",\"2\":\"4015\"},{\"1\":\"25\",\"2\":\"1457\"},{\"1\":\"30\",\"2\":\"4771\"},{\"1\":\"22\",\"2\":\"2733\"},{\"1\":\"42\",\"2\":\"8094\"},{\"1\":\"33\",\"2\":\"1851\"},{\"1\":\"23\",\"2\":\"3215\"},{\"1\":\"58\",\"2\":\"8780\"},{\"1\":\"35\",\"2\":\"8268\"},{\"1\":\"44\",\"2\":\"7915\"},{\"1\":\"11\",\"2\":\"44\"},{\"1\":\"38\",\"2\":\"1810\"},{\"1\":\"62\",\"2\":\"7623\"},{\"1\":\"51\",\"2\":\"5442\"},{\"1\":\"11\",\"2\":\"33\"},{\"1\":\"58\",\"2\":\"2758\"},{\"1\":\"54\",\"2\":\"9398\"},{\"1\":\"34\",\"2\":\"6580\"},{\"1\":\"25\",\"2\":\"191\"},{\"1\":\"22\",\"2\":\"4375\"},{\"1\":\"14\",\"2\":\"12\"},{\"1\":\"11\",\"2\":\"83\"},{\"1\":\"54\",\"2\":\"7865\"},{\"1\":\"52\",\"2\":\"8559\"},{\"1\":\"17\",\"2\":\"4374\"},{\"1\":\"23\",\"2\":\"463\"},{\"1\":\"18\",\"2\":\"969\"},{\"1\":\"60\",\"2\":\"4588\"},{\"1\":\"14\",\"2\":\"99\"},{\"1\":\"30\",\"2\":\"3439\"},{\"1\":\"37\",\"2\":\"8247\"},{\"1\":\"43\",\"2\":\"3010\"},{\"1\":\"43\",\"2\":\"4068\"},{\"1\":\"24\",\"2\":\"2954\"},{\"1\":\"16\",\"2\":\"44\"},{\"1\":\"33\",\"2\":\"3201\"},{\"1\":\"34\",\"2\":\"7972\"},{\"1\":\"49\",\"2\":\"7183\"},{\"1\":\"7\",\"2\":\"2\"},{\"1\":\"20\",\"2\":\"2936\"},{\"1\":\"61\",\"2\":\"5310\"},{\"1\":\"34\",\"2\":\"6737\"},{\"1\":\"4\",\"2\":\"19\"},{\"1\":\"41\",\"2\":\"7439\"},{\"1\":\"5\",\"2\":\"74\"},{\"1\":\"30\",\"2\":\"4327\"},{\"1\":\"30\",\"2\":\"4537\"},{\"1\":\"14\",\"2\":\"28\"},{\"1\":\"56\",\"2\":\"9955\"},{\"1\":\"61\",\"2\":\"3358\"},{\"1\":\"51\",\"2\":\"9310\"},{\"1\":\"68\",\"2\":\"636\"},{\"1\":\"10\",\"2\":\"52\"},{\"1\":\"33\",\"2\":\"3676\"},{\"1\":\"46\",\"2\":\"10217\"},{\"1\":\"6\",\"2\":\"86\"},{\"1\":\"17\",\"2\":\"3347\"},{\"1\":\"28\",\"2\":\"1100\"},{\"1\":\"33\",\"2\":\"4542\"},{\"1\":\"59\",\"2\":\"6122\"},{\"1\":\"77\",\"2\":\"1159\"},{\"1\":\"35\",\"2\":\"2150\"},{\"1\":\"22\",\"2\":\"3237\"},{\"1\":\"56\",\"2\":\"5130\"},{\"1\":\"24\",\"2\":\"4085\"},{\"1\":\"25\",\"2\":\"3373\"},{\"1\":\"30\",\"2\":\"4420\"},{\"1\":\"43\",\"2\":\"3894\"},{\"1\":\"3\",\"2\":\"66\"},{\"1\":\"31\",\"2\":\"4070\"},{\"1\":\"11\",\"2\":\"46\"},{\"1\":\"12\",\"2\":\"44\"},{\"1\":\"51\",\"2\":\"9436\"},{\"1\":\"6\",\"2\":\"64\"},{\"1\":\"39\",\"2\":\"6701\"},{\"1\":\"27\",\"2\":\"20\"},{\"1\":\"70\",\"2\":\"1862\"},{\"1\":\"20\",\"2\":\"1707\"},{\"1\":\"26\",\"2\":\"4436\"},{\"1\":\"57\",\"2\":\"4987\"},{\"1\":\"17\",\"2\":\"2431\"},{\"1\":\"30\",\"2\":\"7829\"},{\"1\":\"14\",\"2\":\"93\"},{\"1\":\"9\",\"2\":\"56\"},{\"1\":\"59\",\"2\":\"9461\"},{\"1\":\"21\",\"2\":\"867\"},{\"1\":\"25\",\"2\":\"3025\"},{\"1\":\"14\",\"2\":\"61\"},{\"1\":\"30\",\"2\":\"5554\"},{\"1\":\"34\",\"2\":\"1654\"},{\"1\":\"33\",\"2\":\"3221\"},{\"1\":\"7\",\"2\":\"70\"},{\"1\":\"14\",\"2\":\"82\"},{\"1\":\"35\",\"2\":\"6229\"},{\"1\":\"37\",\"2\":\"5039\"},{\"1\":\"51\",\"2\":\"3110\"},{\"1\":\"37\",\"2\":\"7088\"},{\"1\":\"38\",\"2\":\"1781\"},{\"1\":\"24\",\"2\":\"1543\"},{\"1\":\"17\",\"2\":\"2641\"},{\"1\":\"41\",\"2\":\"9779\"},{\"1\":\"8\",\"2\":\"15\"},{\"1\":\"19\",\"2\":\"1925\"},{\"1\":\"17\",\"2\":\"1962\"},{\"1\":\"55\",\"2\":\"6732\"},{\"1\":\"38\",\"2\":\"3501\"},{\"1\":\"19\",\"2\":\"2984\"},{\"1\":\"45\",\"2\":\"6354\"},{\"1\":\"7\",\"2\":\"17\"},{\"1\":\"36\",\"2\":\"5608\"},{\"1\":\"19\",\"2\":\"369\"},{\"1\":\"22\",\"2\":\"4480\"},{\"1\":\"67\",\"2\":\"275\"},{\"1\":\"26\",\"2\":\"811\"},{\"1\":\"36\",\"2\":\"5398\"},{\"1\":\"51\",\"2\":\"7607\"},{\"1\":\"27\",\"2\":\"1638\"},{\"1\":\"40\",\"2\":\"8335\"},{\"1\":\"43\",\"2\":\"8305\"},{\"1\":\"15\",\"2\":\"95\"},{\"1\":\"14\",\"2\":\"85\"},{\"1\":\"27\",\"2\":\"2478\"},{\"1\":\"37\",\"2\":\"7488\"},{\"1\":\"13\",\"2\":\"72\"},{\"1\":\"30\",\"2\":\"3954\"},{\"1\":\"72\",\"2\":\"707\"},{\"1\":\"37\",\"2\":\"7204\"},{\"1\":\"37\",\"2\":\"4205\"},{\"1\":\"15\",\"2\":\"71\"},{\"1\":\"20\",\"2\":\"3257\"},{\"1\":\"2\",\"2\":\"11\"},{\"1\":\"39\",\"2\":\"5066\"},{\"1\":\"36\",\"2\":\"4909\"},{\"1\":\"52\",\"2\":\"9656\"},{\"1\":\"8\",\"2\":\"48\"},{\"1\":\"3\",\"2\":\"43\"},{\"1\":\"8\",\"2\":\"65\"},{\"1\":\"51\",\"2\":\"3115\"},{\"1\":\"44\",\"2\":\"4902\"},{\"1\":\"21\",\"2\":\"3475\"},{\"1\":\"60\",\"2\":\"8746\"},{\"1\":\"22\",\"2\":\"2866\"},{\"1\":\"9\",\"2\":\"39\"},{\"1\":\"19\",\"2\":\"1748\"},{\"1\":\"32\",\"2\":\"2764\"},{\"1\":\"30\",\"2\":\"6687\"},{\"1\":\"38\",\"2\":\"4196\"},{\"1\":\"28\",\"2\":\"2823\"},{\"1\":\"59\",\"2\":\"5269\"},{\"1\":\"32\",\"2\":\"2247\"},{\"1\":\"24\",\"2\":\"3261\"},{\"1\":\"46\",\"2\":\"6958\"},{\"1\":\"53\",\"2\":\"9342\"},{\"1\":\"38\",\"2\":\"2408\"},{\"1\":\"24\",\"2\":\"2109\"},{\"1\":\"42\",\"2\":\"9196\"},{\"1\":\"16\",\"2\":\"42\"},{\"1\":\"69\",\"2\":\"2503\"},{\"1\":\"54\",\"2\":\"8916\"},{\"1\":\"9\",\"2\":\"71\"},{\"1\":\"27\",\"2\":\"1521\"},{\"1\":\"34\",\"2\":\"2350\"},{\"1\":\"48\",\"2\":\"3794\"},{\"1\":\"23\",\"2\":\"2321\"},{\"1\":\"6\",\"2\":\"22\"},{\"1\":\"48\",\"2\":\"3983\"},{\"1\":\"75\",\"2\":\"2551\"},{\"1\":\"15\",\"2\":\"6\"},{\"1\":\"3\",\"2\":\"85\"},{\"1\":\"72\",\"2\":\"2525\"},{\"1\":\"26\",\"2\":\"2132\"},{\"1\":\"62\",\"2\":\"10269\"},{\"1\":\"8\",\"2\":\"72\"},{\"1\":\"25\",\"2\":\"1987\"},{\"1\":\"28\",\"2\":\"2618\"},{\"1\":\"16\",\"2\":\"79\"},{\"1\":\"29\",\"2\":\"2899\"},{\"1\":\"49\",\"2\":\"9442\"},{\"1\":\"38\",\"2\":\"6772\"},{\"1\":\"58\",\"2\":\"3731\"},{\"1\":\"68\",\"2\":\"2100\"},{\"1\":\"32\",\"2\":\"6876\"},{\"1\":\"65\",\"2\":\"6818\"},{\"1\":\"52\",\"2\":\"8781\"},{\"1\":\"26\",\"2\":\"3012\"},{\"1\":\"95\",\"2\":\"2374\"},{\"1\":\"45\",\"2\":\"6352\"},{\"1\":\"47\",\"2\":\"7531\"},{\"1\":\"38\",\"2\":\"4819\"},{\"1\":\"31\",\"2\":\"2049\"},{\"1\":\"26\",\"2\":\"4373\"},{\"1\":\"74\",\"2\":\"301\"},{\"1\":\"14\",\"2\":\"50\"},{\"1\":\"1\",\"2\":\"65\"},{\"1\":\"39\",\"2\":\"6782\"},{\"1\":\"15\",\"2\":\"15\"},{\"1\":\"11\",\"2\":\"67\"},{\"1\":\"55\",\"2\":\"6198\"},{\"1\":\"69\",\"2\":\"1922\"},{\"1\":\"35\",\"2\":\"2604\"},{\"1\":\"19\",\"2\":\"718\"},{\"1\":\"23\",\"2\":\"2648\"},{\"1\":\"15\",\"2\":\"98\"},{\"1\":\"41\",\"2\":\"4222\"},{\"1\":\"50\",\"2\":\"2432\"},{\"1\":\"8\",\"2\":\"90\"},{\"1\":\"54\",\"2\":\"5986\"},{\"1\":\"40\",\"2\":\"4133\"},{\"1\":\"53\",\"2\":\"4555\"},{\"1\":\"51\",\"2\":\"3912\"},{\"1\":\"11\",\"2\":\"77\"},{\"1\":\"26\",\"2\":\"2838\"},{\"1\":\"15\",\"2\":\"81\"},{\"1\":\"32\",\"2\":\"4608\"},{\"1\":\"42\",\"2\":\"5529\"},{\"1\":\"29\",\"2\":\"1818\"},{\"1\":\"51\",\"2\":\"8469\"},{\"1\":\"9\",\"2\":\"37\"},{\"1\":\"52\",\"2\":\"7072\"},{\"1\":\"45\",\"2\":\"6029\"},{\"1\":\"8\",\"2\":\"82\"},{\"1\":\"23\",\"2\":\"1222\"},{\"1\":\"24\",\"2\":\"2440\"},{\"1\":\"44\",\"2\":\"10179\"},{\"1\":\"19\",\"2\":\"1981\"},{\"1\":\"52\",\"2\":\"4262\"},{\"1\":\"35\",\"2\":\"5502\"},{\"1\":\"72\",\"2\":\"2458\"},{\"1\":\"64\",\"2\":\"3325\"},{\"1\":\"39\",\"2\":\"1976\"},{\"1\":\"73\",\"2\":\"2635\"},{\"1\":\"16\",\"2\":\"71\"},{\"1\":\"32\",\"2\":\"7228\"},{\"1\":\"10\",\"2\":\"32\"},{\"1\":\"88\",\"2\":\"801\"},{\"1\":\"13\",\"2\":\"20\"},{\"1\":\"88\",\"2\":\"1398\"},{\"1\":\"33\",\"2\":\"5901\"},{\"1\":\"32\",\"2\":\"2777\"},{\"1\":\"21\",\"2\":\"2396\"},{\"1\":\"8\",\"2\":\"64\"},{\"1\":\"6\",\"2\":\"62\"},{\"1\":\"60\",\"2\":\"3345\"},{\"1\":\"33\",\"2\":\"2855\"},{\"1\":\"30\",\"2\":\"3872\"},{\"1\":\"40\",\"2\":\"8362\"},{\"1\":\"25\",\"2\":\"2641\"},{\"1\":\"21\",\"2\":\"377\"},{\"1\":\"8\",\"2\":\"32\"},{\"1\":\"11\",\"2\":\"54\"},{\"1\":\"28\",\"2\":\"580\"},{\"1\":\"18\",\"2\":\"1068\"},{\"1\":\"25\",\"2\":\"2983\"},{\"1\":\"6\",\"2\":\"15\"},{\"1\":\"46\",\"2\":\"10003\"},{\"1\":\"39\",\"2\":\"6831\"},{\"1\":\"38\",\"2\":\"2404\"},{\"1\":\"20\",\"2\":\"1255\"},{\"1\":\"57\",\"2\":\"5465\"},{\"1\":\"43\",\"2\":\"9091\"},{\"1\":\"37\",\"2\":\"3440\"},{\"1\":\"37\",\"2\":\"3085\"},{\"1\":\"83\",\"2\":\"543\"},{\"1\":\"11\",\"2\":\"96\"},{\"1\":\"34\",\"2\":\"6230\"},{\"1\":\"67\",\"2\":\"1181\"},{\"1\":\"28\",\"2\":\"975\"},{\"1\":\"32\",\"2\":\"6264\"},{\"1\":\"12\",\"2\":\"19\"},{\"1\":\"43\",\"2\":\"8358\"},{\"1\":\"30\",\"2\":\"6525\"},{\"1\":\"31\",\"2\":\"8147\"},{\"1\":\"5\",\"2\":\"22\"},{\"1\":\"6\",\"2\":\"44\"},{\"1\":\"33\",\"2\":\"3269\"},{\"1\":\"72\",\"2\":\"2016\"},{\"1\":\"60\",\"2\":\"8208\"},{\"1\":\"61\",\"2\":\"7949\"},{\"1\":\"10\",\"2\":\"16\"},{\"1\":\"44\",\"2\":\"6201\"},{\"1\":\"15\",\"2\":\"63\"},{\"1\":\"50\",\"2\":\"10371\"},{\"1\":\"18\",\"2\":\"2040\"},{\"1\":\"40\",\"2\":\"3337\"},{\"1\":\"31\",\"2\":\"2162\"},{\"1\":\"7\",\"2\":\"8\"},{\"1\":\"58\",\"2\":\"9886\"},{\"1\":\"56\",\"2\":\"9461\"},{\"1\":\"32\",\"2\":\"6234\"},{\"1\":\"27\",\"2\":\"3669\"},{\"1\":\"46\",\"2\":\"4210\"},{\"1\":\"44\",\"2\":\"4378\"},{\"1\":\"43\",\"2\":\"3372\"},{\"1\":\"14\",\"2\":\"92\"},{\"1\":\"46\",\"2\":\"8807\"},{\"1\":\"4\",\"2\":\"76\"},{\"1\":\"21\",\"2\":\"891\"},{\"1\":\"10\",\"2\":\"56\"},{\"1\":\"44\",\"2\":\"4846\"},{\"1\":\"18\",\"2\":\"2382\"},{\"1\":\"30\",\"2\":\"4924\"},{\"1\":\"32\",\"2\":\"1819\"},{\"1\":\"25\",\"2\":\"1270\"},{\"1\":\"28\",\"2\":\"3780\"},{\"1\":\"32\",\"2\":\"6800\"},{\"1\":\"43\",\"2\":\"8250\"},{\"1\":\"36\",\"2\":\"3837\"},{\"1\":\"24\",\"2\":\"3124\"},{\"1\":\"60\",\"2\":\"7138\"},{\"1\":\"18\",\"2\":\"550\"},{\"1\":\"46\",\"2\":\"8443\"},{\"1\":\"19\",\"2\":\"307\"},{\"1\":\"63\",\"2\":\"7764\"},{\"1\":\"23\",\"2\":\"2912\"},{\"1\":\"40\",\"2\":\"4655\"},{\"1\":\"32\",\"2\":\"3149\"},{\"1\":\"27\",\"2\":\"2207\"},{\"1\":\"26\",\"2\":\"1365\"},{\"1\":\"48\",\"2\":\"6035\"},{\"1\":\"20\",\"2\":\"72\"},{\"1\":\"26\",\"2\":\"1507\"},{\"1\":\"70\",\"2\":\"774\"},{\"1\":\"11\",\"2\":\"12\"},{\"1\":\"38\",\"2\":\"1936\"},{\"1\":\"16\",\"2\":\"32\"},{\"1\":\"13\",\"2\":\"61\"},{\"1\":\"13\",\"2\":\"3\"},{\"1\":\"49\",\"2\":\"5250\"},{\"1\":\"21\",\"2\":\"256\"},{\"1\":\"45\",\"2\":\"6340\"},{\"1\":\"23\",\"2\":\"1929\"},{\"1\":\"28\",\"2\":\"3451\"},{\"1\":\"56\",\"2\":\"10170\"},{\"1\":\"32\",\"2\":\"4776\"},{\"1\":\"16\",\"2\":\"72\"},{\"1\":\"28\",\"2\":\"3004\"},{\"1\":\"20\",\"2\":\"3473\"},{\"1\":\"17\",\"2\":\"3203\"},{\"1\":\"10\",\"2\":\"44\"},{\"1\":\"27\",\"2\":\"4479\"},{\"1\":\"84\",\"2\":\"1680\"},{\"1\":\"20\",\"2\":\"767\"},{\"1\":\"8\",\"2\":\"1\"},{\"1\":\"7\",\"2\":\"43\"},{\"1\":\"22\",\"2\":\"2402\"},{\"1\":\"14\",\"2\":\"59\"},{\"1\":\"8\",\"2\":\"100\"},{\"1\":\"46\",\"2\":\"8311\"},{\"1\":\"45\",\"2\":\"9021\"},{\"1\":\"27\",\"2\":\"3684\"},{\"1\":\"41\",\"2\":\"3914\"},{\"1\":\"51\",\"2\":\"3929\"},{\"1\":\"32\",\"2\":\"7405\"},{\"1\":\"64\",\"2\":\"7602\"},{\"1\":\"34\",\"2\":\"2756\"},{\"1\":\"55\",\"2\":\"6226\"},{\"1\":\"29\",\"2\":\"3664\"},{\"1\":\"72\",\"2\":\"1012\"},{\"1\":\"18\",\"2\":\"3782\"},{\"1\":\"46\",\"2\":\"3561\"},{\"1\":\"21\",\"2\":\"3272\"},{\"1\":\"42\",\"2\":\"9524\"},{\"1\":\"17\",\"2\":\"653\"},{\"1\":\"42\",\"2\":\"7575\"},{\"1\":\"16\",\"2\":\"10\"},{\"1\":\"3\",\"2\":\"52\"},{\"1\":\"39\",\"2\":\"8070\"},{\"1\":\"61\",\"2\":\"7255\"},{\"1\":\"50\",\"2\":\"7487\"},{\"1\":\"35\",\"2\":\"8443\"},{\"1\":\"63\",\"2\":\"3981\"},{\"1\":\"27\",\"2\":\"4101\"},{\"1\":\"48\",\"2\":\"5163\"},{\"1\":\"33\",\"2\":\"3373\"},{\"1\":\"36\",\"2\":\"3000\"},{\"1\":\"18\",\"2\":\"2876\"},{\"1\":\"39\",\"2\":\"3414\"},{\"1\":\"61\",\"2\":\"5692\"},{\"1\":\"47\",\"2\":\"9798\"},{\"1\":\"13\",\"2\":\"88\"},{\"1\":\"5\",\"2\":\"86\"},{\"1\":\"74\",\"2\":\"2850\"},{\"1\":\"26\",\"2\":\"2091\"},{\"1\":\"31\",\"2\":\"5227\"},{\"1\":\"12\",\"2\":\"11\"},{\"1\":\"31\",\"2\":\"3234\"},{\"1\":\"29\",\"2\":\"7970\"},{\"1\":\"48\",\"2\":\"7639\"},{\"1\":\"31\",\"2\":\"1508\"},{\"1\":\"51\",\"2\":\"8616\"},{\"1\":\"22\",\"2\":\"1005\"},{\"1\":\"60\",\"2\":\"5714\"},{\"1\":\"18\",\"2\":\"2845\"},{\"1\":\"15\",\"2\":\"29\"},{\"1\":\"6\",\"2\":\"6\"},{\"1\":\"85\",\"2\":\"1250\"},{\"1\":\"15\",\"2\":\"32\"},{\"1\":\"15\",\"2\":\"32\"},{\"1\":\"35\",\"2\":\"2283\"},{\"1\":\"51\",\"2\":\"8073\"},{\"1\":\"28\",\"2\":\"2841\"},{\"1\":\"57\",\"2\":\"5325\"},{\"1\":\"53\",\"2\":\"9983\"},{\"1\":\"18\",\"2\":\"2518\"},{\"1\":\"41\",\"2\":\"6028\"},{\"1\":\"72\",\"2\":\"2345\"},{\"1\":\"8\",\"2\":\"50\"},{\"1\":\"33\",\"2\":\"7044\"},{\"1\":\"36\",\"2\":\"6528\"},{\"1\":\"8\",\"2\":\"92\"},{\"1\":\"32\",\"2\":\"5611\"},{\"1\":\"58\",\"2\":\"4989\"},{\"1\":\"71\",\"2\":\"1021\"},{\"1\":\"63\",\"2\":\"3147\"},{\"1\":\"42\",\"2\":\"7811\"},{\"1\":\"55\",\"2\":\"8942\"},{\"1\":\"46\",\"2\":\"5165\"},{\"1\":\"17\",\"2\":\"2519\"},{\"1\":\"23\",\"2\":\"721\"},{\"1\":\"30\",\"2\":\"4044\"},{\"1\":\"39\",\"2\":\"6515\"},{\"1\":\"64\",\"2\":\"4402\"},{\"1\":\"24\",\"2\":\"1146\"},{\"1\":\"34\",\"2\":\"2628\"},{\"1\":\"56\",\"2\":\"3377\"},{\"1\":\"58\",\"2\":\"6260\"},{\"1\":\"43\",\"2\":\"10383\"},{\"1\":\"16\",\"2\":\"3\"},{\"1\":\"25\",\"2\":\"1245\"},{\"1\":\"50\",\"2\":\"5292\"},{\"1\":\"21\",\"2\":\"1945\"},{\"1\":\"91\",\"2\":\"1780\"},{\"1\":\"16\",\"2\":\"67\"},{\"1\":\"9\",\"2\":\"69\"},{\"1\":\"33\",\"2\":\"4956\"},{\"1\":\"17\",\"2\":\"1364\"},{\"1\":\"29\",\"2\":\"4755\"},{\"1\":\"15\",\"2\":\"14\"},{\"1\":\"11\",\"2\":\"2\"},{\"1\":\"50\",\"2\":\"6363\"},{\"1\":\"31\",\"2\":\"7181\"},{\"1\":\"26\",\"2\":\"159\"},{\"1\":\"41\",\"2\":\"9950\"},{\"1\":\"39\",\"2\":\"3336\"},{\"1\":\"64\",\"2\":\"6459\"},{\"1\":\"36\",\"2\":\"6062\"},{\"1\":\"37\",\"2\":\"6996\"},{\"1\":\"31\",\"2\":\"4809\"},{\"1\":\"28\",\"2\":\"3312\"},{\"1\":\"33\",\"2\":\"5665\"},{\"1\":\"16\",\"2\":\"53\"},{\"1\":\"27\",\"2\":\"406\"},{\"1\":\"22\",\"2\":\"4272\"},{\"1\":\"36\",\"2\":\"6277\"},{\"1\":\"48\",\"2\":\"6630\"},{\"1\":\"22\",\"2\":\"439\"},{\"1\":\"29\",\"2\":\"3253\"},{\"1\":\"47\",\"2\":\"5584\"},{\"1\":\"60\",\"2\":\"5703\"},{\"1\":\"31\",\"2\":\"4291\"},{\"1\":\"44\",\"2\":\"3356\"},{\"1\":\"19\",\"2\":\"2490\"},{\"1\":\"26\",\"2\":\"1646\"},{\"1\":\"33\",\"2\":\"2392\"},{\"1\":\"43\",\"2\":\"8660\"},{\"1\":\"43\",\"2\":\"5959\"},{\"1\":\"15\",\"2\":\"81\"},{\"1\":\"58\",\"2\":\"9016\"},{\"1\":\"19\",\"2\":\"1183\"},{\"1\":\"5\",\"2\":\"15\"},{\"1\":\"33\",\"2\":\"4285\"},{\"1\":\"15\",\"2\":\"99\"},{\"1\":\"48\",\"2\":\"8447\"},{\"1\":\"24\",\"2\":\"3532\"},{\"1\":\"50\",\"2\":\"3235\"},{\"1\":\"27\",\"2\":\"701\"},{\"1\":\"24\",\"2\":\"2782\"},{\"1\":\"21\",\"2\":\"2042\"},{\"1\":\"52\",\"2\":\"9535\"},{\"1\":\"35\",\"2\":\"5983\"},{\"1\":\"44\",\"2\":\"6705\"},{\"1\":\"32\",\"2\":\"3036\"},{\"1\":\"20\",\"2\":\"2980\"},{\"1\":\"44\",\"2\":\"10485\"},{\"1\":\"6\",\"2\":\"29\"},{\"1\":\"37\",\"2\":\"4501\"},{\"1\":\"57\",\"2\":\"9828\"},{\"1\":\"24\",\"2\":\"2975\"},{\"1\":\"43\",\"2\":\"9093\"},{\"1\":\"37\",\"2\":\"6955\"},{\"1\":\"24\",\"2\":\"3370\"},{\"1\":\"32\",\"2\":\"1693\"},{\"1\":\"65\",\"2\":\"6600\"},{\"1\":\"11\",\"2\":\"65\"},{\"1\":\"21\",\"2\":\"2901\"},{\"1\":\"61\",\"2\":\"6239\"},{\"1\":\"64\",\"2\":\"5506\"},{\"1\":\"41\",\"2\":\"2394\"},{\"1\":\"9\",\"2\":\"89\"},{\"1\":\"51\",\"2\":\"8823\"},{\"1\":\"24\",\"2\":\"2952\"},{\"1\":\"41\",\"2\":\"3231\"},{\"1\":\"21\",\"2\":\"546\"},{\"1\":\"54\",\"2\":\"3790\"},{\"1\":\"52\",\"2\":\"4017\"},{\"1\":\"49\",\"2\":\"10355\"},{\"1\":\"39\",\"2\":\"3329\"},{\"1\":\"47\",\"2\":\"9126\"},{\"1\":\"4\",\"2\":\"65\"},{\"1\":\"72\",\"2\":\"2574\"},{\"1\":\"47\",\"2\":\"9389\"},{\"1\":\"48\",\"2\":\"3127\"},{\"1\":\"13\",\"2\":\"38\"},{\"1\":\"21\",\"2\":\"1195\"},{\"1\":\"60\",\"2\":\"7520\"},{\"1\":\"63\",\"2\":\"6672\"},{\"1\":\"24\",\"2\":\"3947\"},{\"1\":\"39\",\"2\":\"5660\"},{\"1\":\"31\",\"2\":\"2951\"},{\"1\":\"7\",\"2\":\"38\"},{\"1\":\"16\",\"2\":\"35\"},{\"1\":\"12\",\"2\":\"47\"},{\"1\":\"15\",\"2\":\"1\"},{\"1\":\"32\",\"2\":\"4857\"},{\"1\":\"46\",\"2\":\"2252\"},{\"1\":\"71\",\"2\":\"2160\"},{\"1\":\"7\",\"2\":\"55\"},{\"1\":\"42\",\"2\":\"7196\"},{\"1\":\"35\",\"2\":\"4317\"},{\"1\":\"23\",\"2\":\"17\"},{\"1\":\"44\",\"2\":\"2620\"},{\"1\":\"21\",\"2\":\"3363\"},{\"1\":\"13\",\"2\":\"27\"},{\"1\":\"34\",\"2\":\"5320\"},{\"1\":\"17\",\"2\":\"1831\"},{\"1\":\"60\",\"2\":\"9975\"},{\"1\":\"33\",\"2\":\"3336\"},{\"1\":\"59\",\"2\":\"7609\"},{\"1\":\"31\",\"2\":\"3565\"},{\"1\":\"9\",\"2\":\"87\"},{\"1\":\"27\",\"2\":\"124\"},{\"1\":\"28\",\"2\":\"3891\"},{\"1\":\"49\",\"2\":\"10128\"},{\"1\":\"30\",\"2\":\"3761\"},{\"1\":\"23\",\"2\":\"2679\"},{\"1\":\"57\",\"2\":\"2780\"},{\"1\":\"0\",\"2\":\"1\"},{\"1\":\"12\",\"2\":\"7\"},{\"1\":\"38\",\"2\":\"8283\"},{\"1\":\"31\",\"2\":\"6428\"},{\"1\":\"45\",\"2\":\"6775\"},{\"1\":\"51\",\"2\":\"7133\"},{\"1\":\"9\",\"2\":\"97\"},{\"1\":\"49\",\"2\":\"8241\"},{\"1\":\"70\",\"2\":\"1613\"},{\"1\":\"54\",\"2\":\"8361\"},{\"1\":\"70\",\"2\":\"2168\"},{\"1\":\"46\",\"2\":\"2678\"},{\"1\":\"51\",\"2\":\"10076\"},{\"1\":\"75\",\"2\":\"2613\"},{\"1\":\"61\",\"2\":\"4201\"},{\"1\":\"25\",\"2\":\"2314\"},{\"1\":\"25\",\"2\":\"3338\"},{\"1\":\"40\",\"2\":\"1691\"},{\"1\":\"7\",\"2\":\"54\"},{\"1\":\"36\",\"2\":\"3195\"},{\"1\":\"23\",\"2\":\"661\"},{\"1\":\"23\",\"2\":\"3241\"},{\"1\":\"11\",\"2\":\"9\"},{\"1\":\"15\",\"2\":\"69\"},{\"1\":\"24\",\"2\":\"1103\"},{\"1\":\"34\",\"2\":\"6267\"},{\"1\":\"24\",\"2\":\"937\"},{\"1\":\"28\",\"2\":\"3477\"},{\"1\":\"37\",\"2\":\"6653\"},{\"1\":\"16\",\"2\":\"56\"},{\"1\":\"53\",\"2\":\"4215\"},{\"1\":\"10\",\"2\":\"72\"},{\"1\":\"31\",\"2\":\"7003\"},{\"1\":\"5\",\"2\":\"89\"},{\"1\":\"10\",\"2\":\"95\"},{\"1\":\"73\",\"2\":\"1786\"},{\"1\":\"78\",\"2\":\"1559\"},{\"1\":\"66\",\"2\":\"2403\"},{\"1\":\"51\",\"2\":\"9372\"},{\"1\":\"25\",\"2\":\"1116\"},{\"1\":\"5\",\"2\":\"88\"},{\"1\":\"19\",\"2\":\"4194\"},{\"1\":\"35\",\"2\":\"2385\"},{\"1\":\"39\",\"2\":\"6740\"},{\"1\":\"17\",\"2\":\"2562\"},{\"1\":\"63\",\"2\":\"2288\"},{\"1\":\"20\",\"2\":\"773\"},{\"1\":\"11\",\"2\":\"90\"},{\"1\":\"32\",\"2\":\"2589\"},{\"1\":\"23\",\"2\":\"1563\"},{\"1\":\"37\",\"2\":\"4563\"},{\"1\":\"41\",\"2\":\"9722\"},{\"1\":\"49\",\"2\":\"10482\"},{\"1\":\"16\",\"2\":\"38\"},{\"1\":\"39\",\"2\":\"1788\"},{\"1\":\"43\",\"2\":\"6336\"},{\"1\":\"28\",\"2\":\"3033\"},{\"1\":\"17\",\"2\":\"2924\"},{\"1\":\"16\",\"2\":\"97\"},{\"1\":\"64\",\"2\":\"6052\"},{\"1\":\"83\",\"2\":\"466\"},{\"1\":\"8\",\"2\":\"62\"},{\"1\":\"5\",\"2\":\"64\"},{\"1\":\"52\",\"2\":\"8264\"},{\"1\":\"39\",\"2\":\"5498\"},{\"1\":\"27\",\"2\":\"1406\"},{\"1\":\"18\",\"2\":\"1836\"},{\"1\":\"31\",\"2\":\"2992\"},{\"1\":\"58\",\"2\":\"6110\"},{\"1\":\"22\",\"2\":\"2024\"},{\"1\":\"61\",\"2\":\"8171\"},{\"1\":\"53\",\"2\":\"9408\"},{\"1\":\"56\",\"2\":\"7006\"},{\"1\":\"32\",\"2\":\"6842\"},{\"1\":\"14\",\"2\":\"80\"},{\"1\":\"9\",\"2\":\"56\"},{\"1\":\"17\",\"2\":\"1116\"},{\"1\":\"31\",\"2\":\"2571\"},{\"1\":\"26\",\"2\":\"2754\"},{\"1\":\"40\",\"2\":\"3781\"},{\"1\":\"19\",\"2\":\"2429\"},{\"1\":\"59\",\"2\":\"9192\"},{\"1\":\"13\",\"2\":\"91\"},{\"1\":\"2\",\"2\":\"56\"},{\"1\":\"27\",\"2\":\"3759\"},{\"1\":\"53\",\"2\":\"4042\"},{\"1\":\"57\",\"2\":\"9083\"},{\"1\":\"34\",\"2\":\"4953\"},{\"1\":\"28\",\"2\":\"1312\"},{\"1\":\"18\",\"2\":\"3625\"},{\"1\":\"14\",\"2\":\"61\"},{\"1\":\"24\",\"2\":\"2915\"},{\"1\":\"40\",\"2\":\"7414\"},{\"1\":\"59\",\"2\":\"3086\"},{\"1\":\"33\",\"2\":\"3960\"},{\"1\":\"63\",\"2\":\"8719\"},{\"1\":\"78\",\"2\":\"2647\"},{\"1\":\"14\",\"2\":\"28\"},{\"1\":\"34\",\"2\":\"5336\"},{\"1\":\"43\",\"2\":\"9639\"},{\"1\":\"44\",\"2\":\"3639\"},{\"1\":\"22\",\"2\":\"2645\"},{\"1\":\"34\",\"2\":\"3833\"},{\"1\":\"58\",\"2\":\"8870\"},{\"1\":\"22\",\"2\":\"3267\"},{\"1\":\"46\",\"2\":\"8270\"},{\"1\":\"35\",\"2\":\"1833\"},{\"1\":\"31\",\"2\":\"5741\"},{\"1\":\"14\",\"2\":\"27\"},{\"1\":\"17\",\"2\":\"3923\"},{\"1\":\"35\",\"2\":\"6379\"},{\"1\":\"22\",\"2\":\"4428\"},{\"1\":\"35\",\"2\":\"6622\"},{\"1\":\"35\",\"2\":\"7634\"},{\"1\":\"24\",\"2\":\"764\"},{\"1\":\"30\",\"2\":\"7467\"},{\"1\":\"32\",\"2\":\"3316\"},{\"1\":\"24\",\"2\":\"3323\"},{\"1\":\"29\",\"2\":\"5829\"},{\"1\":\"26\",\"2\":\"2363\"},{\"1\":\"42\",\"2\":\"7048\"},{\"1\":\"14\",\"2\":\"25\"},{\"1\":\"5\",\"2\":\"5\"},{\"1\":\"13\",\"2\":\"51\"},{\"1\":\"50\",\"2\":\"2278\"},{\"1\":\"63\",\"2\":\"6404\"},{\"1\":\"48\",\"2\":\"3140\"},{\"1\":\"55\",\"2\":\"2346\"},{\"1\":\"5\",\"2\":\"86\"},{\"1\":\"13\",\"2\":\"99\"},{\"1\":\"9\",\"2\":\"79\"},{\"1\":\"48\",\"2\":\"10337\"},{\"1\":\"12\",\"2\":\"86\"},{\"1\":\"44\",\"2\":\"4189\"},{\"1\":\"40\",\"2\":\"2659\"},{\"1\":\"5\",\"2\":\"85\"},{\"1\":\"26\",\"2\":\"3549\"},{\"1\":\"6\",\"2\":\"39\"},{\"1\":\"30\",\"2\":\"8019\"},{\"1\":\"13\",\"2\":\"42\"},{\"1\":\"29\",\"2\":\"6389\"},{\"1\":\"27\",\"2\":\"2543\"},{\"1\":\"19\",\"2\":\"1787\"},{\"1\":\"25\",\"2\":\"2840\"},{\"1\":\"5\",\"2\":\"57\"},{\"1\":\"36\",\"2\":\"3294\"},{\"1\":\"44\",\"2\":\"5694\"},{\"1\":\"52\",\"2\":\"6118\"},{\"1\":\"9\",\"2\":\"90\"},{\"1\":\"56\",\"2\":\"8018\"},{\"1\":\"35\",\"2\":\"7472\"},{\"1\":\"45\",\"2\":\"3867\"},{\"1\":\"24\",\"2\":\"1549\"},{\"1\":\"18\",\"2\":\"919\"},{\"1\":\"13\",\"2\":\"3\"},{\"1\":\"3\",\"2\":\"51\"},{\"1\":\"15\",\"2\":\"6\"},{\"1\":\"30\",\"2\":\"8208\"},{\"1\":\"20\",\"2\":\"1842\"},{\"1\":\"41\",\"2\":\"10436\"},{\"1\":\"61\",\"2\":\"2726\"},{\"1\":\"10\",\"2\":\"58\"},{\"1\":\"55\",\"2\":\"6045\"},{\"1\":\"26\",\"2\":\"2396\"},{\"1\":\"33\",\"2\":\"6175\"},{\"1\":\"20\",\"2\":\"2273\"},{\"1\":\"20\",\"2\":\"1698\"},{\"1\":\"25\",\"2\":\"2151\"},{\"1\":\"25\",\"2\":\"897\"},{\"1\":\"24\",\"2\":\"2671\"},{\"1\":\"45\",\"2\":\"3646\"},{\"1\":\"20\",\"2\":\"82\"},{\"1\":\"44\",\"2\":\"2484\"},{\"1\":\"9\",\"2\":\"89\"},{\"1\":\"17\",\"2\":\"432\"},{\"1\":\"20\",\"2\":\"4206\"},{\"1\":\"53\",\"2\":\"5942\"},{\"1\":\"22\",\"2\":\"2828\"},{\"1\":\"56\",\"2\":\"9328\"},{\"1\":\"37\",\"2\":\"4994\"},{\"1\":\"19\",\"2\":\"1901\"},{\"1\":\"50\",\"2\":\"9621\"},{\"1\":\"25\",\"2\":\"509\"},{\"1\":\"5\",\"2\":\"39\"},{\"1\":\"70\",\"2\":\"823\"},{\"1\":\"52\",\"2\":\"7069\"},{\"1\":\"46\",\"2\":\"2616\"},{\"1\":\"16\",\"2\":\"1\"},{\"1\":\"8\",\"2\":\"49\"},{\"1\":\"14\",\"2\":\"46\"},{\"1\":\"29\",\"2\":\"2399\"},{\"1\":\"59\",\"2\":\"9083\"},{\"1\":\"13\",\"2\":\"25\"},{\"1\":\"25\",\"2\":\"3326\"},{\"1\":\"36\",\"2\":\"3839\"},{\"1\":\"99\",\"2\":\"1065\"},{\"1\":\"30\",\"2\":\"5314\"},{\"1\":\"36\",\"2\":\"2017\"},{\"1\":\"33\",\"2\":\"1780\"},{\"1\":\"32\",\"2\":\"4258\"},{\"1\":\"38\",\"2\":\"5771\"},{\"1\":\"51\",\"2\":\"5026\"},{\"1\":\"20\",\"2\":\"1976\"},{\"1\":\"42\",\"2\":\"7090\"},{\"1\":\"38\",\"2\":\"2882\"},{\"1\":\"40\",\"2\":\"4365\"},{\"1\":\"28\",\"2\":\"0\"},{\"1\":\"14\",\"2\":\"26\"},{\"1\":\"8\",\"2\":\"94\"},{\"1\":\"35\",\"2\":\"6898\"},{\"1\":\"77\",\"2\":\"147\"},{\"1\":\"14\",\"2\":\"32\"},{\"1\":\"9\",\"2\":\"92\"},{\"1\":\"26\",\"2\":\"4039\"},{\"1\":\"51\",\"2\":\"8642\"},{\"1\":\"30\",\"2\":\"5117\"},{\"1\":\"35\",\"2\":\"3336\"},{\"1\":\"15\",\"2\":\"31\"},{\"1\":\"19\",\"2\":\"4096\"},{\"1\":\"45\",\"2\":\"5572\"},{\"1\":\"37\",\"2\":\"4511\"},{\"1\":\"35\",\"2\":\"3918\"},{\"1\":\"41\",\"2\":\"3564\"},{\"1\":\"64\",\"2\":\"5996\"},{\"1\":\"10\",\"2\":\"24\"},{\"1\":\"60\",\"2\":\"9743\"},{\"1\":\"15\",\"2\":\"33\"},{\"1\":\"19\",\"2\":\"919\"},{\"1\":\"29\",\"2\":\"2826\"},{\"1\":\"51\",\"2\":\"3829\"},{\"1\":\"27\",\"2\":\"499\"},{\"1\":\"30\",\"2\":\"6117\"},{\"1\":\"10\",\"2\":\"65\"},{\"1\":\"12\",\"2\":\"75\"},{\"1\":\"26\",\"2\":\"1824\"},{\"1\":\"48\",\"2\":\"3963\"},{\"1\":\"60\",\"2\":\"5064\"},{\"1\":\"68\",\"2\":\"956\"},{\"1\":\"73\",\"2\":\"1689\"},{\"1\":\"37\",\"2\":\"7826\"},{\"1\":\"32\",\"2\":\"8394\"},{\"1\":\"54\",\"2\":\"3012\"},{\"1\":\"46\",\"2\":\"5954\"},{\"1\":\"32\",\"2\":\"7917\"},{\"1\":\"39\",\"2\":\"3026\"},{\"1\":\"8\",\"2\":\"36\"},{\"1\":\"32\",\"2\":\"6202\"},{\"1\":\"31\",\"2\":\"6571\"},{\"1\":\"24\",\"2\":\"2801\"},{\"1\":\"28\",\"2\":\"574\"},{\"1\":\"21\",\"2\":\"1430\"},{\"1\":\"40\",\"2\":\"1509\"},{\"1\":\"49\",\"2\":\"7048\"},{\"1\":\"77\",\"2\":\"1886\"},{\"1\":\"40\",\"2\":\"7034\"},{\"1\":\"44\",\"2\":\"8073\"},{\"1\":\"53\",\"2\":\"4127\"},{\"1\":\"39\",\"2\":\"5472\"},{\"1\":\"34\",\"2\":\"4420\"},{\"1\":\"47\",\"2\":\"6235\"},{\"1\":\"11\",\"2\":\"39\"},{\"1\":\"11\",\"2\":\"19\"},{\"1\":\"25\",\"2\":\"156\"},{\"1\":\"20\",\"2\":\"1961\"},{\"1\":\"39\",\"2\":\"1949\"},{\"1\":\"29\",\"2\":\"5844\"},{\"1\":\"6\",\"2\":\"83\"},{\"1\":\"32\",\"2\":\"2880\"},{\"1\":\"57\",\"2\":\"6897\"},{\"1\":\"80\",\"2\":\"1415\"},{\"1\":\"19\",\"2\":\"3158\"},{\"1\":\"5\",\"2\":\"71\"},{\"1\":\"67\",\"2\":\"1713\"},{\"1\":\"43\",\"2\":\"3764\"},{\"1\":\"17\",\"2\":\"2312\"},{\"1\":\"2\",\"2\":\"83\"},{\"1\":\"47\",\"2\":\"2460\"},{\"1\":\"24\",\"2\":\"2592\"},{\"1\":\"9\",\"2\":\"6\"},{\"1\":\"52\",\"2\":\"6049\"},{\"1\":\"46\",\"2\":\"9207\"},{\"1\":\"47\",\"2\":\"6180\"},{\"1\":\"25\",\"2\":\"3614\"},{\"1\":\"4\",\"2\":\"22\"},{\"1\":\"14\",\"2\":\"11\"},{\"1\":\"50\",\"2\":\"2439\"},{\"1\":\"54\",\"2\":\"8241\"},{\"1\":\"46\",\"2\":\"10380\"},{\"1\":\"39\",\"2\":\"5613\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Question 1\n\n------------------------------------------------------------------------\n\nFor each variable, compute the following values. You can use the built-in functions or use the mathematical formulas.\\\n- expected value, variance, standard deviation\n\n> computing the mean, variance and standard deviation\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-2_a25cee10c965721dda92dea69a1e145b'}\n\n```{.r .cell-code}\n# for Age\nexpected_value_age <- mean(random_vars$age)\nvariance_age <- var(random_vars$age)\nstandard_deviation_age <- sd(random_vars$age)\n\n# for Income\nexpected_value_income <- mean(random_vars$income)\nvariance_income <- var(random_vars$income)\nstandard_deviation_income <- sd(random_vars$income)\n```\n:::\n\n\n> Printing mean, variance, standard deviation for age\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-3_f72e20229a404159fae029364a697971'}\n\n```{.r .cell-code}\ncat(\"# Expected Value:  =\", expected_value_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Expected Value:  = 33.471\n```\n:::\n\n```{.r .cell-code}\ncat(\"# Variance Value:  =\", variance_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Variance Value:  = 340.6078\n```\n:::\n\n```{.r .cell-code}\ncat(\"# Standard Deviation Value:  =\", standard_deviation_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Standard Deviation Value:  = 18.45556\n```\n:::\n:::\n\n\n> Printing mean, variance, standard deviation for Income\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-4_2bf5b04dbe0f302714078236113c02ce'}\n\n```{.r .cell-code}\ncat(\"# Expected Value:  =\", expected_value_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Expected Value:  = 3510.731\n```\n:::\n\n```{.r .cell-code}\ncat(\"# Variance Value:  =\", variance_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Variance Value:  = 8625646\n```\n:::\n\n```{.r .cell-code}\ncat(\"# Standard Deviation Value:  =\", standard_deviation_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Standard Deviation Value:  = 2936.945\n```\n:::\n:::\n\n\n# Question 2\n\n------------------------------------------------------------------------\n\n**The standard deviations cannot be for atleast the provided dataset. The reason being, the variables assessed are age and income, which are measured in two different units and completely different scales. Therefore, it would not be ideal to compare these standard deviations.**\n\n**The figures below are the plots of the Standard deviation of both Age and Income. We can see the scales and the distribution are completely different.**\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-5_d0202550bde0cd11df9dadceaf2885f6'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(random_vars, aes(x = age)) +\n  geom_histogram(binwidth = 1, fill = 'blue', alpha = 0.7) +\n  geom_vline(aes(xintercept = expected_value_age), color = \"red\", linetype = \"dashed\", size = 1) +\n  geom_vline(aes(xintercept = expected_value_age + standard_deviation_age), color = \"red\", size = 1) +\n  geom_vline(aes(xintercept = expected_value_age - standard_deviation_age), color = \"red\", size = 1) +\n  ggtitle(\"Distribution of Age with Standard Deviation\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\n#> ℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](02_statistics_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot for 'income'\nggplot(random_vars, aes(x = income)) +\n  geom_histogram(binwidth = 100, fill = 'green', alpha = 0.7) +\n  geom_vline(aes(xintercept = expected_value_income), color = \"blue\", linetype = \"dashed\", size = 1) +\n  geom_vline(aes(xintercept = expected_value_income + standard_deviation_income), color = \"blue\", size = 1) +\n  geom_vline(aes(xintercept = expected_value_income - standard_deviation_income), color = \"blue\", size = 1) +\n  ggtitle(\"Distribution of Income with Standard Deviation\")\n```\n\n::: {.cell-output-display}\n![](02_statistics_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\n# Question 3\n\nThen, examine the relationship between both variables and compute:\\\n- covariance, correlation\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-6_059bffa75824f85e5edcb9b4233be572'}\n\n```{.r .cell-code}\ncovariance <- cov(random_vars$age, random_vars$income)\ncorrelation <- cor(random_vars$age, random_vars$income)\n```\n:::\n\n\n> Printing covariance and correlation\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-7_cffe33b96b1261c4bdb4e0dd12b17e63'}\n\n```{.r .cell-code}\ncat(\"# Covariance:  =\", covariance)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Covariance:  = 29700.15\n```\n:::\n\n```{.r .cell-code}\ncat(\"# Correlation:  =\", correlation)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # Correlation:  = 0.5479432\n```\n:::\n:::\n\n\n# Question 4\n\n------------------------------------------------------------------------\n\n**Correlation is a relatively easier measure to interpret. It is dimensionless and can provide information on the strength of the relationship between two variables, which makes it a perfect measure to compare Age and Income when these variables are fundamentally on two different scales. It is standardized to a range of -1 to 1, where the sign indicates the direction of the relationship, and the magnitude indicates the strength.**\n\n*As the age increases, the income tends to increase as well, roughly accounting for 54.8%. This does not imply causation but there is a tendency for income to rise as the age rises.*\n\n**On the other hand, Covariance is 29700.15. This value does not seem to be sensible between age and income. These variables have two different scales, which directly have an effect on the value of the Covariance.**\n\n# Question 5\n\n------------------------------------------------------------------------\n\nCompute the conditional expected value for:\\\n- E\\[income\\|age \\<= 18\\]\\\n- E\\[income\\|age ∈ \\[18, 65\\]\\]\\\n- E\\[income\\|age \\>= 65\\]\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-8_861403d2fdbe1fde5c637d364c43a388'}\n\n```{.r .cell-code}\nexpected_value_teens <- mean(random_vars$income[random_vars$age <= 18])\nexpected_value_adults <- mean(random_vars$income[random_vars$age > 18 & random_vars$age <= 65])\nexpected_value_seniors <- mean(random_vars$income[random_vars$age > 65])\n```\n:::\n\n\n> Printing covariance and correlation\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-9_fd30370ede490670c38177ed5e0d1548'}\n\n```{.r .cell-code}\ncat(\"# E[income|age <= 18]:  =\", expected_value_teens)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # E[income|age <= 18]:  = 389.6074\n```\n:::\n\n```{.r .cell-code}\ncat(\"# E[income|age ∈ [18, 65]]:  =\", expected_value_adults)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # E[income|age ∈ [18, 65]]:  = 4743.234\n```\n:::\n\n```{.r .cell-code}\ncat(\"# E[income|age >= 65]:  =\", expected_value_seniors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # E[income|age >= 65]:  = 1604.193\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}